#!/usr/bin/perl
use strict; use warnings;

# ============================================================================
#  SINGLE SOURCE OF TRUTH for the canonical base URL.
#  >>> AT DOMAIN-SWITCH TIME: change ONLY the $BASE line below to
#  >>> 'https://navexcapital.com' and set $NOINDEX = 0, then re-run:  perl tools/build-meta.pl
#  Every absolute og:url / og:image / twitter:image / canonical / sitemap / manifest
#  URL on the whole site is regenerated from $BASE. Nothing else to touch.
# ============================================================================
my $BASE    = 'https://navex-zeta.vercel.app';   # <-- THE ONE LINE (current live origin so previews work TODAY)
my $NOINDEX = 1;                                  # 1 = staging (noindex); set 0 at launch

my $SITE = "/Users/salihdurmus/Desktop/navex-build/site";
my $OGALT = "Navex Capital, operator-led maritime, transport and logistics advisory";

# page file => canonical path
my @pages = (
  ["index.html","/"],
  ["services.html","/services.html"],
  ["industries.html","/industries.html"],
  ["case-studies.html","/case-studies.html"],
  ["about.html","/about.html"],
  ["insights.html","/insights.html"],
  ["contact.html","/contact.html"],
  ["privacy.html","/privacy.html"],
  ["terms.html","/terms.html"],
  ["404.html","/404.html"],
);

for my $p (@pages) {
  my ($file,$path) = @$p;
  my $fp = "$SITE/$file";
  unless (-f $fp) { print "skip (missing): $file\n"; next; }
  open my $fh,'<',$fp or die $!; local $/; my $c=<$fh>; close $fh;

  my ($title) = $c =~ /<title>(.*?)<\/title>/s;  $title //= 'Navex Capital';
  my ($desc)  = $c =~ /<meta name="description" content="(.*?)"\s*\/?>/s; $desc //= '';

  # strip any previously-generated block + legacy managed tags
  $c =~ s/[ \t]*<!-- META:START.*?META:END -->\n?//s;
  $c =~ s/^[ \t]*<meta name="robots"[^>]*>\s*\n//mig;
  $c =~ s/^[ \t]*<link rel="canonical"[^>]*>\s*\n//mig;
  $c =~ s/^[ \t]*<meta property="og:[^>]*>\s*\n//mig;
  $c =~ s/^[ \t]*<meta name="twitter:[^>]*>\s*\n//mig;
  $c =~ s/^[ \t]*<link rel="icon"[^>]*>\s*\n//mig;
  $c =~ s/^[ \t]*<link rel="apple-touch-icon"[^>]*>\s*\n//mig;
  $c =~ s/^[ \t]*<link rel="manifest"[^>]*>\s*\n//mig;
  $c =~ s/^[ \t]*<meta name="theme-color"[^>]*>\s*\n//mig;

  my $noindex = ($NOINDEX || $file eq '404.html')
    ? "  <meta name=\"robots\" content=\"noindex\" />\n" : "";
  my $url = $BASE . $path;
  my $img = "$BASE/assets/og-image.jpg";

  my $block = "  <!-- META:START (generated by tools/build-meta.pl from \$BASE) -->\n"
    . $noindex
    . "  <link rel=\"canonical\" href=\"$url\" />\n"
    . "  <meta property=\"og:type\" content=\"website\" />\n"
    . "  <meta property=\"og:site_name\" content=\"Navex Capital\" />\n"
    . "  <meta property=\"og:locale\" content=\"en_US\" />\n"
    . "  <meta property=\"og:title\" content=\"$title\" />\n"
    . "  <meta property=\"og:description\" content=\"$desc\" />\n"
    . "  <meta property=\"og:url\" content=\"$url\" />\n"
    . "  <meta property=\"og:image\" content=\"$img\" />\n"
    . "  <meta property=\"og:image:width\" content=\"1200\" />\n"
    . "  <meta property=\"og:image:height\" content=\"630\" />\n"
    . "  <meta property=\"og:image:alt\" content=\"$OGALT\" />\n"
    . "  <meta name=\"twitter:card\" content=\"summary_large_image\" />\n"
    . "  <meta name=\"twitter:title\" content=\"$title\" />\n"
    . "  <meta name=\"twitter:description\" content=\"$desc\" />\n"
    . "  <meta name=\"twitter:image\" content=\"$img\" />\n"
    . "  <meta name=\"twitter:image:alt\" content=\"$OGALT\" />\n"
    . "  <link rel=\"icon\" href=\"/favicon.svg\" type=\"image/svg+xml\" />\n"
    . "  <link rel=\"icon\" href=\"/favicon.ico\" sizes=\"32x32\" />\n"
    . "  <link rel=\"apple-touch-icon\" href=\"/assets/apple-touch-icon.png\" />\n"
    . "  <link rel=\"manifest\" href=\"/site.webmanifest\" />\n"
    . "  <meta name=\"theme-color\" content=\"#13293C\" />\n"
    . "  <!-- META:END -->\n";

  # insert right after the description meta line
  $c =~ s/(<meta name="description" content="[^"]*"\s*\/?>\n)/$1$block/;

  open my $out,'>',$fp or die $!; print $out $c; close $out;
  print "ok: $file\n";
}

# ---- robots.txt (permissive so link-preview scrapers are never blocked; noindex meta handles search) ----
open my $r,'>',"$SITE/robots.txt" or die $!;
print $r "User-agent: *\nAllow: /\nSitemap: $BASE/sitemap.xml\n";
close $r; print "wrote robots.txt\n";

# ---- sitemap.xml ----
open my $sm,'>',"$SITE/sitemap.xml" or die $!;
print $sm qq{<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n};
for my $p (@pages) { next if $p->[0] eq '404.html'; print $sm "  <url><loc>$BASE$p->[1]</loc></url>\n"; }
print $sm "</urlset>\n"; close $sm; print "wrote sitemap.xml\n";

# ---- site.webmanifest ----
open my $wm,'>',"$SITE/site.webmanifest" or die $!;
print $wm qq({\n  "name": "Navex Capital",\n  "short_name": "Navex",\n  "theme_color": "#13293C",\n  "background_color": "#13293C",\n  "display": "standalone",\n  "start_url": "/",\n  "icons": [\n    { "src": "/assets/apple-touch-icon.png", "sizes": "180x180", "type": "image/png" },\n    { "src": "/favicon.svg", "type": "image/svg+xml", "sizes": "any" }\n  ]\n}\n);
close $wm; print "wrote site.webmanifest\n";

print "DONE (BASE=$BASE NOINDEX=$NOINDEX)\n";
